displayName=Timers CA
author=PaJau
description=Timers for some bosses listed in Combat Achievements
tags=pajau,vardorvis,leviathan,duke sucellus,whisperer,vorkath,zulrah,hespori,muspah,yama,maggot
plugins=com.TimersCA.TimersCAPlugin
build=standard
version=1.9.2